### ISSUE TITLE
Create unsubscribe observable mixin

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#120]
Should we create an unsubscribe observable mixin? This would automatically handle creating an unsubscribe observable which calls `.next()` and `.complete()` in the `ngOnDestroy()` function. However this would come with the downside there is no in-built linting to detect if observables are being properly unsubscribed. The implementation of this solution would be harder to enforce during reviews.

Example mixin code:

```typescript
function WithDestroy<T extends Constructor<{}>>(Base: T = (class {} as any)) {
  return class extends Base implements OnDestroy {
    destroy$  = new Subject<void>()

    ngOnDestroy() {
      this.destroy$.next();
    }
  }
}
```

**Comment by Allcharles** [comment]
I'd like your opinion on this @atruskie

**Comment by atruskie** [comment]
I'm vaguely aware observables have long lives and need to be unsubscribed from. I'm not entirely sure what problem this is solving?

How is the mixin used in a real class? How does that real class register the observable to be destroyed?

**Comment by Allcharles** [comment]
This is how observables are currently dealt with:

```typescript
export class Component extends PageComponent implements OnInit, OnDestroy {
  private unsubscribe = new Subject();

  constructor(private api: ProjectsService) {
    super();
  }

  ngOnInit() {
    this.api
      .create(new Project($event))
      .pipe(takeUntil(this.unsubscribe))
      .subscribe(<<INSERT LOGIC>>);
  }

  ngOnDestroy() {
    this.unsubscribe.next();
    this.unsubscribe.complete();
  }
}
```

The proposed changes will change it to this:

```typescript
export class Component extends WithDestroy(PageComponent) implements OnInit {
  constructor(private api: ProjectsService) {
    super();
  }

  ngOnInit() {
    this.api
      .create(new Project($event))
      .pipe(takeUntil(this.unsubscribe))
      .subscribe(<<INSERT LOGIC>>);
  }
}
```

The main difference is that I no longer have to a) define an `unsubscribe` observable, and b) call its destruction in the `ngOnDestroy` function. Functionally both of these components are the same, it's just that I have to repeat the code for creating and destroying the `unsubscribe` observable in every single class which uses an observable which is a lot of redundant code for something that may be handled automatically in the future.

Relevant excerpt from link:

> In response Ben mentions that there are discussions right now to allow Observables to hook into the Angular component lifecycle events and Ward suggests an Observable of lifecycle events that a component could subscribe to as a way of knowing when to complete Observables maintained as component internal state.

Relevant link: https://stackoverflow.com/questions/38008334/angular-rxjs-when-should-i-unsubscribe-from-subscription

**Comment by atruskie** [comment]
One last question: can we fold this into `PageComponent` - that is our class after all. That would simplify the inheritance and make this common utility to all of our page components.

**Comment by Allcharles** [comment]
Yup, putting it into the `PageComponent` is fairly simple and shouldn't block any access to `ngOnDestroy()`.
