### ISSUE TITLE
Production SSR fails to load styles.scss

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#1300]
The production SSR environment does not properly include the styles.scss file. This causes the theme of the website to not properly load, and causes some visual issues.

**Comment by atruskie** [comment]
I don't see how we could achieve this using a dynamic configuration,

- unless we have content holes that SSR co-operatively renders
- or we pre-render on deploy

The later is probably ideal: in the docker file we can change the entrypoint script to start pre-rendering while SSR is running.

**Comment by Allcharles** [comment]
Example of the issue which is occurring: 
![image](https://user-images.githubusercontent.com/3955116/130880834-82ec57f7-6304-4431-90f2-6580a6fa9d10.png)
