### ISSUE TITLE
Work In Progress Labels

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#14]
Project should contain a work in progress (WIP) component which wraps another component to display to the developer and user that the current page is not functional. It should have the following features:

- In production/staging:
  - [x] Display bootstrap warning class text above component declaring page a WIP
  - [x] Disable submit button for forms
  - [x] Add tool-tip to form submit button informing them that the button does not work
- In development
  - [x] Display bootstrap warning class text above component declaring page a WIP
  - [x] Change submit button form forms to bootstrap warning class
  - [x] Add tool-tip to form submit button informing dev that this button currently does not work

Edit: Refined submit button colour choice courtesy of atruskie

**Comment by atruskie** [comment]
Rather than red tints, I'd suggest using bootstrap's warning colour/class.
