### ISSUE TITLE
Caching Resources

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#16]
Application could receive a significant performance boost with the additional caching of internal and external resources. This will also improve the Google Audit score improving website visibility.

Related links:
https://angularfirebase.com/lessons/installable-angular-progressive-web-app/
https://medium.com/codingthesmartway-com-blog/angular-5-service-worker-b722e571e306
https://en.wikipedia.org/wiki/HTTP/2_Server_Push
https://developers.google.com/web/fundamentals/web-app-manifest
https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

**Comment by atruskie** [comment]
This is low priority for now. 

Is there anything you need from me?

**Comment by Allcharles** [comment]
Nah, should be farely simple to set-up, I'll probably get around to it if I get stuck on something else.
