### ISSUE TITLE
Abstract model cleanup

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#173]
- [x] Renamed `redirectPath` to something more descriptive
- [x] Cleanup `toJSON` implementations to remove non-editable fields
- [x] Change `notes` datatype from `string` to `object/hash`
  - `notes` inputs are json blobs
  - Potentially need to use this: [class](https://github.com/eligrey/Blob.js) (recommended by [angular](https://angular.io/guide/browser-support#suggested-polyfills))

**Comment by Allcharles** [comment]
Could potentially include model association as part of this. Some relevant links:

- https://github.com/creativecuriositystudio/modelsafe
- https://github.com/WavyWalk/front-model
- https://www.graphiti.dev/js/index
  - Best option found
  - When integrated in project, causes `RangeError: Maximum call stack size exceeded`

[JSON API](https://jsonapi.org/) based solutions:

- https://github.com/ghidoz/angular2-jsonapi
- https://github.com/reyesoft/ngx-jsonapi

**Comment by atruskie** [comment]
Re optons:

1. last change from last year, abondoned?
2. almost no adoption
3. graphiti looks interesting but it also assumes JSON API backend

**Comment by Allcharles** [comment]
Okay, here is my current plan:

```typescript
import type SitesService from './sites.service'

class Project {
  @Association(SitesService)
  siteIds: Ids

  // Created by association decorator
  associations = {
    siteIds: SitesService
  }
}
```

Option 1:

ProjectsService
```typescript
@Injectable()
class ProjectsService {
  list()
  filter()
  show()
  create()
  update()
  destroy()

  association(project, key) {
    const service = injector.inject(project.associations[key]);
    if (project[key] instanceof 'set') {
      return service.filter({ filter: { project.kind : { eq: { project.id } } } });
    } else {
      return service.show(project[key], project);
   }
  }
}
```

Option 2:

ApiSevice
```typescript
@Injectable()
class ApiService {
  projects = ProjectService;
  sites = SitesService;
  shallowSites = ShallowSitesService;

  association(model, key) {
    // Check list of loaded serviced, else
    if (this.shallowSites) {
      const service = this.shallowSites;
    } else  {
      const service = injector.inject(model.associations[key]);
    }

    if (project[key] instanceof 'set') {
      return service.filter({ filter: { model.kind : { eq: { model.id } } } });
    } else {
      return service.show(model[key], model);
   }
  }
}
```

Option 3

Preferred option, try to get injections functional on the AbstractModel class. This could work if I figured out how to get DI functional inside the class. Without DI, I'm forced to use the `Injector` function from @angular/core which requires a full import (instead of a type import which mayyyyy be able to get around the circular dependencies).
