### ISSUE TITLE
Create JSON schema for FormlyFieldConfig

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#181]
Create a [JSON Schema](https://json-schema.org/) for the `.json` files which are imported by components for use with the `<app-form>` and `<app-detail-view` components. It should validate to the same/similar definition as `FormlyFieldConfig`.

**Comment by atruskie** [comment]
I don't think this is needed.

The json stored in files should be plain old json schema.

https://formly.dev/examples/advanced/json-schema
https://stackblitz.com/angular/ryrprexmqpe?file=src%2Fassets%2Fjson-schema%2Fselect_alternatives.json
