### ISSUE TITLE
Google Analytics Tag

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#19]
Add google analytics to website. This should utilise the following module: https://github.com/revolunet/angular-google-analytics

**Comment by atruskie** [comment]
An alternate guide that seems useful as a cross-reference: https://medium.com/better-programming/how-to-properly-add-google-analytics-tracking-to-your-angular-web-app-bc7750713c9e

**Comment by atruskie** [comment]
Marking as high priority since our site has been deployed for a few months now and we've missed all the analytics.
