### ISSUE TITLE
Known Baw Services

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#219]
Create the following services:

- [x] Account (`/user_accounts`)
- [x] Analysis Jobs (`/analysis_jobs`)
- [x] Analysis Job Items (`/analysis_jobs/:analysis_job_id/audio_recordings`)
- [ ] Analysis Results (`/analysis_jobs/:analysisJobId/results{path}`)
- [x] Audio Events (`/audio_recordings/:audioRecordingId/audio_events`)
- [x] Audio Event Tag (`/audio_recordings/:recordingId/audio_events/:audioEventId/tags/filter`)
- [x] Audio Recording (`/audio_recordings/:audioRecordingId`)
- [x] Bookmarks (`/bookmarks`)
- [x] Dataset (`/datasets`)
- [x] Dataset Items (`/datasets/:datasetId/item`)
- [x] Progress Events (`/progress_events`)
- [x] Projects (`/projects`)
- [x] Questions (`/questions` `/studies/:studyId/questions`)
- [x] Responses (`/responses` `/studies/:studyId/responses`)
- [x] Saved Searches (`/saved_searches`)
- [x] Scripts (`/scripts`)
- [x] Sites (`/sites` `/projects/:id/sites`)
- [x] Studies (`/studies`)
- [x] Tags (`/tags`)
- [x] Tag Groups (`/tag_groups`)
- [x] Taggings (`/audio_recordings/:recordingId/audio_events/:audioEventId/taggings`)
- [x] User (`/my_account`)

**Comment by Allcharles** [comment]
Immutable services:

- Scripts (CR)
- SavedSearches (though they can be deleted) (CRD)
- ProgressEvents (are a time-series event recorder) (CR)
- DatasetItems  (though they can be deleted) (CRD)


Readonly services:

- AnalysisJobItem (R)
- AudioRecordings (from client's perspective) (R)
- AnalysisJobs (most fields become readonly after job creation, though things like _Description_ and _Name_ can still be edited) (RU)

Deprecated services:

- AudioEventComment

**Comment by Allcharles** [comment]
Analysis Results will be implemented another time because it is not a baw model. It instead returns a collection of files and folders.

**Comment by atruskie** [comment]
Well AnalysisJobitems has a model, it's just dynamically constructed. Here is the old model: https://github.com/QutEcoacoustics/baw-client/blob/master/src/components/models/analysisResult.js

And the old services: https://github.com/QutEcoacoustics/baw-client/tree/master/src/components/services/analysisResult

You'll need the analsysis result service to port the visualize page
