### ISSUE TITLE
feat:RenderView image view FieldStyling

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#220]
Add option to `RenderViewComponent` so that images can be viewed. This likely will work by checking in the `fields` input if the value is of type image.

**Comment by atruskie** [comment]
Probably, it should use another component, `baw-image-thumbnail` which will accept one of the API returned image objects, choose the appropriately sized thumbnail to load, and show it.

**Comment by Allcharles** [comment]
I should extract this to a reusable component for other parts of the application. Specifically the header and the badge components could be simplified with the component.

**Comment by Allcharles** [comment]
This has been implemented, @atruskie is it worth it to still create a `baw-image-thumnail` component? I've found that getting stylings to work on images inside an angular component makes them a nightmare.

**Comment by atruskie** [comment]
so in theory, all a thumbnail component would do would be to choose a smaller image in an array of images.

I don't see much need at the moment, but we might need such a component later
