### ISSUE TITLE
Improving model decorators

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#229]
List of improvements for model decorators:

- [x] Possible to improve association decorator typing using `keyof` similar to Jasmine `spyOn` function where methods can be provided as a string representing the key:
  ```typescript
  @HasMany(SHALLOW_SITE, (m: Project) => m.siteIds, (m:Project) => m.secondKey, ...)
  // vs
  @HasMany(SHALLOW_SITE, "siteIds", "secondKey", ...)
  ```
  - This would somewhat simplify the Association Decorator code as the key can be used instead of the callback function
- [x] Possible to add typing to attribute decorator using a similar method to the one discussed above. Currently the key option is not type checked.
- [ ] ~Potentially standardise `@BawPersistAttr` decorator to follow the same system as other decorators. i.e.~
  ```typescript
  @BawAttribute({persist: true})
  ```
  - However this is based on the premise that `@BawAttribute` by itself would have some purpose
  - Could be an idea just to turn it into a function so that it is at least the same format as the other decorators
- [ ] Attempt to add more intelligent warnings, currently models will spam the console when an associated model's primary key is null or undefined
- [ ] Somehow remove the need for `InjectionTokens` (eg. `SHALLOW_SITE`), currently `InjectionTokens` are used as a workaround to prevent cyclic dependencies between models
- [x] Simplify associated model output.
  ```typescript
  projects.sites // observable
  // vs
  projects.sites // array
  ```
- [ ] Re-introduce access to associated model observable

**Comment by atruskie** [comment]
1. Replacing lambda with stirng key: that is a **great** idea using `keyof` - as long as it is type checked, which it should be
2. It'll be interesting to see if this works. It'd involve mapped types?
3. I think that's more ceremony. Why does turning `it into a function so that it is at least the same format as the other decorators` net us?
4. 👍
5. It'll be interesting to see

**Comment by Allcharles** [comment]
4. Is possible if we pass an options field to the decorator (ie: `{required: true}`). Haven't implemented just yet as its only the one option and something may come up later which exposes a better method. Passing a required option would allow us to change the severity of the warning based on whether the associated model should exist or not

**Comment by Allcharles** [comment]
1 and 2. Current solution in PR #236 uses the model instead of its interface. Technically the interface should be used because the model gives access to keys not connected to the database. However using the model allows for type checking that the input is an AbstractModel
