### ISSUE TITLE
Add sanitization to image payloads

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#232]
Currently images are not sanitized before being displayed on the website. The following steps should happen before displaying an image:

- Check if URL matches API host (i.e. staging.ecosounds)
- Validate image: https://stackoverflow.com/questions/18837735/check-if-image-exists-on-server-using-javascript

This can be automated by creating `@BawImage` and `@BawImages` decorators for models

**Comment by atruskie** [comment]
I don't think you need to do the 404 check - the browser can do that for you.

If the image does not exist you can use a fallback method (either `onerror` or a css back image)

**Comment by Allcharles** [comment]
My plan was to replace the URL with a default value if 404. For example, if a users profile icon fails to load, display the default profile icon instead

**Comment by atruskie** [comment]
Yeah you can do both of those with fallback methods that obviate the need for the manual server call.

Here's a react article that demonstrates the `onerror` and css approaches (before devolving into other chaos): https://medium.com/@webcore1/react-fallback-for-broken-images-strategy-a8dfa9c1be1e

**Comment by Allcharles** [comment]
Plan:

- Create a new decorator for Abstract Models which handles converting image urls to an array containing the image received from the server as well as details. In the event of an array of image urls being return, sort by largest to smallest with default as last option
- Create an image directive which:
  - Changes the src so that it accepts an array of src urls and selects the first value in the array
  - Appends authToken to image url
  - Accepts a `thumbnailSize` input which allows the developer to specify which array value to display based on size
