### ISSUE TITLE
Improper nullish checking

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#255]
Nullish checking of model parameters sometimes does not handle edge cases where numbers are 0 or strings are empty. This should be rectified using the `value == null` command to properly evaluate if a value is `undefined` or `null`. Additional tests should be written for components which handle models to validate that the edge cases are being handled properly.

It may be worth adding nullish coalescing operators to models to properly handle setting default values: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator.

## Example:

```typescript
if (!model.id) {
  // This will hit the edge case id = 0
}
if (!model.name) {
  // This will hit the edge case name = ""
}
```

Should instead be

```typescript
if (model.id == null) {
  // This will return true only if id = undefined or null
}
if (model.name == null) {
  // This will return true only if name = undefined or null
}
```

**Comment by Allcharles** [comment]
Potentially create a helper function which can make this logic more clear.

Example:

```typescript
function isInstantiated(value: any) {
  return value !== undefined && value !== null;
}
```

**Comment by atruskie** [comment]
that helper could have the type refined to a generic, and also act as a TS type guard
