### ISSUE TITLE
Fix the CI

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/workbench-client#31]
We need to get continuous integration build working ASAP.

**Comment by Allcharles** [comment]
I can fix it, currently the thing blocking the unit tests from passing is the fetch command for the external configuration (environment) doesn't run before tests. If I remember correctly there are also a couple tests which fail to correctly handle the rxjs subscriptions which can cause race condition failures sometimes

**Comment by Allcharles** [comment]
@atruskie Just need you to to review the azure pipelines output to see if it is to your liking

**Comment by atruskie** [comment]
Looks excellent. Nice work.
