### ISSUE TITLE
Systematic check of dates & times, ensuring timezone formatting

### ISSUE THREAD

**Issue by JessieLOliver** [QutEcoacoustics/workbench-client#345]
Time zones must not be browser dependent, and instead constant to when the recordings were taken, so that people from around the world can evaluate audio data according to when it was recorded
- The challenge is displaying time in a format that is intuitive to users
- Most UI avoid showing times in other timezones at **all** costs.
- There are a few screens where times in multiple timezones may need to be displayed
- More feedback appreciated on this issue in particular from other designers/researchers how they show multiple timezones in a user interface!

Related to https://github.com/QutBioacoustics/baw-server/issues/279

**Comment by Allcharles** [comment]
Relates to #346
