### ISSUE TITLE
Model description markup

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#379]
Currently, when models are displayed, the system uses the models `description` parameter. This should instead be changed to `descriptionHtml` where relevant (such as the details pages). Allowing HTML injection however is a potential point of attack and research should be done into evaluating which is a safe method of accepting it onto the page. Maybe only allow whitelisted html elements if possible?

**Comment by atruskie** [comment]
I'm pretty sure the server sanitizes description inputs (markdown) when they are submitted. The `*_html` fields are the rendered versions of the markdown.

**Comment by Allcharles** [comment]
Definitely worth keeping in mind, if there is a simple method of sanitising inputs use it. Otherwise its not a blocking requirement.

**Comment by Allcharles** [comment]
Another thing which should be addressed as part of this issue is the length of description fields. For `baw-cards`, the description length should be limited so that the card is of reasonable length (4-5 lines?). This can either be achieved by either using a library to replace the over-length text with ..., or using the css ellipsis text-overflow property.

**Comment by Allcharles** [comment]
Some possible libraries to achieve the above comment:

- https://github.com/nzambello/ellipsed
- https://github.com/DiZhou92/ngx-line-truncation
- https://github.com/glinford/ellipsis.js
- https://github.com/yowainwright/shave
