### ISSUE TITLE
404 Route

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#4]
Currently there is no Page Not Found Route. There is a technical limitation with this as it requires the following route:

```javascript
{ path: '**', component: PageNotFoundComponent }
```

However, this route must be the last route added to the router module, and this is an issue because we are lazily loading routes. Adding this directly to the `app-routing.module.ts` will have the application ignore all dynamically added routes.

**Comment by atruskie** [comment]
https://stackoverflow.com/questions/54998822/angular-404-page-routing-for-nested-modules

https://stackoverflow.com/questions/56898153/angular-8-nested-routing-using-children-and-respective-route-modules-upto-three

https://stackoverflow.com/questions/40015385/angular-2-router-wildcard-handling-with-child-routes
