### ISSUE TITLE
Automatically bump project version using semvar

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#414]
Update the CI so that the version of the project is updated using some version of semvar. This can either be achieved by using specific commit names to trigger the CI, or using labels on PRs. The goal of this is to achieve automatic version bumps to the project with minimal effort from the programmer. Ideally, the solution should also work with a changelog generator.

Relevant links:
- https://github.com/actions-ecosystem/action-release-label

**Comment by atruskie** [comment]
Note:

- I'm not a fan of semver for applications. calver works better.
- You don't need the GA action-release-label if you choose to use one of the conventional changelog generators

**Comment by Allcharles** [comment]
Closed in PR #1048
