### ISSUE TITLE
List projects limited to 25

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#424]
The list of projects a user can view is currently limited to 25. This limit should either be removed, or pagination is added to allow the user to filter/search through additional projects.

**Comment by atruskie** [comment]
Yeah, we should pagination.

Along with a type ahead filter.

I normally hate infinite scroll, but infinite scroll pagination would be fine in this case - as long as when the user navigates back to such a page they are placed in the right spot.

**Comment by Allcharles** [comment]
This draws into the ui comments from this issue: #225
