### ISSUE TITLE
Investigate speeding up compile time using Nx Cloud

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#463]
Nx Cloud offers to speed up compile time by up to 10 times. This is performed by maintaining compiled versions of the local files, with recompilation only happening with modified files. Currently the angular cli only performs this for the node_modules libraries. This library will NOT improve the compile time of the CI, only the dev computer on repeat builds.

Relevant Link: https://nx.app/angular-cli-faster

**Comment by atruskie** [comment]
It should work on the CI too: https://nx.app/faq , https://twitter.com/victorsavkin/status/1273996050643156995
