### ISSUE TITLE
Content Management System (CMS)

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#49]
Content management system should enable the website to retrieve `.html` files from the BAW API.

Feature set:

- Sanitise HTML to reduce risk of XSS (https://angular.io/api/platform-browser/DomSanitizer)
- Convert CMS page internal routes to use the angular routing system (https://github.com/QutEcoacoustics/workbench-client/issues/49#issuecomment-565868825)
- Insert data into CMS page (https://github.com/QutEcoacoustics/workbench-client/issues/49#issuecomment-572854175)
- Allow CMS to provide custom CSS styling?

**Comment by atruskie** [comment]
So we'll be using a pre-built CMS. In particular a [headless](https://headlesscms.org/) one.

We're not going to build and part of the CMS or include any module in the angular app.

Whichever service we use, and including the ones we have now, we'll always return HTML to the client

**Comment by Allcharles** [comment]
Another big issue for the CMS service is how we are going to handle internal routes from the HTML blobs. We can convert any '/' routes to use the router module however this leaves the opportunity for the CMS files to become out of sync whenever a route is changed.

**Comment by Allcharles** [comment]
Found another issue for the CMS service; how can we pass data to the CMS page? An example of this is the harvest page which changes its instructions to guide the user on how to harvest audio for a specific project and site. We could make this part of the angular app, however 99% of the page is just text which should be on the CMS.

**Comment by Allcharles** [comment]
Potential solution to adding links (both internal and external) to CMS pages: https://medium.com/@adrianfaciu/using-the-angular-router-to-navigate-to-external-links-15cc585b7b88

**Comment by Allcharles** [comment]
Another issue attached to this is determining how to best retrieve CMS files from the server. Currently, the cms file paths are stored in a config which is sent to the workbench-client. Inside the workbench-client, a manually written (and updated) typing for the CMS files is maintained as a way of ensuring values exist. This is not a long term solution if the number of CMS files dramatically increases.

**Comment by atruskie** [comment]
> Found another issue for the CMS service; how can we pass data to the CMS page? An example of this is the harvest page which changes its instructions to guide the user on how to harvest audio for a specific project and site. We could make this part of the angular app, however 99% of the page is just text which should be on the CMS.

We'll use a custom helper, like https://github.com/QutEcoacoustics/baw-server/blob/master/app/helpers/cms_helpers.rb.
Those functions are exposed to CMS pages (safely). From there we can pull data from route info or QSP.



> Another issue attached to this is determining how to best retrieve CMS files from the server. Currently, the cms file paths are stored in a config which is sent to the workbench-client. Inside the workbench-client, a manually written (and updated) typing for the CMS files is maintained as a way of ensuring values exist. This is not a long term solution if the number of CMS files dramatically increases.

Currently the site has 5 (maybe 6) well known pages that are guaranteed to exist. We'll use the slugs of those pages as constant opaque string keys and encode them into the app.

They're in here: https://github.com/QutEcoacoustics/baw-server/blob/master/db/cms_seeds/cms_seeds.rb

Summarized:
- /
- /credits
- /data_upload
- /ethics
- /privacy'
- /harvest_instructions (not yet implemented)

The CMS does have a JSON API that can be used to retrieve a listing of pages but I don't think we need to use that.

**Comment by Allcharles** [comment]
Related comment:

> this would be a candidate image that could be moved to the CMS. Not sure how it would actually work.
> 
> CMS has support for uploading arbitrary files. If we could assign them to a category, then use API to fetch a random one from category...

https://github.com/QutEcoacoustics/workbench-client/pull/541#discussion_r507407460
