### ISSUE TITLE
Improve indentation system on secondary links

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#58]
Currently, links added to the secondary links menu have to specify how many indentations they require. This can however be determined by counting its number of parents.

This information can be gathered from here:
secondary-menu.component.ts
```javascript
const parentMenuRoutes: MenuRoute[] = [];
let menuRoute = current;
while (menuRoute.parent) {
  menuRoute = menuRoute.parent;
  parentMenuRoutes.push(menuRoute);
}
```

This would reduce the amount of information that must be know before compile time in the `PageComponents`, as well as potentially allowing the same component to have two direct parents.

**Comment by atruskie** [comment]
Sounds good
