### ISSUE TITLE
Form Submission Load Spinner

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#6]
When forms are submitted, there is currently no feedback to the user that the submit button has been pressed. Either the submit button should be replaced by a spinner (or just plain disabled) while the submit function runs, otherwise a message should appear at the top (similar to the error message) stating the form is submitting. The current state could confuse users when network responses are long such as BadRequest's.

**Comment by atruskie** [comment]
I'd suggest disabling submit buttons by default.

Then couple that with this library https://github.com/aitboudad/ngx-loading-bar which will automatically show progress bars for every page and http request.

**Comment by Allcharles** [comment]
Closed in f9b1a10168f6f0a4064655b195a3c86d5c77173c
