### ISSUE TITLE
add SSR tests to CI

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/workbench-client#613]
**Is your feature request related to a problem? Please describe.**

Related to https://github.com/QutEcoacoustics/workbench-client/pull/601/files#diff-18813c86948efc57e661623d7ba48ff94325c9b5421ec9177f724922dd553a35R29

We should be testing our SSR container in the CI workflow.

**Describe the solution you'd like**

For now, the simplest possible build and test of docker container and SSR:

- separate job in CI
- build the container
- start the container
- curl to fetch home page 
- grep results to check environment.json file has taken effect

The SSR client won't work since it does not have a live backend to point to. This is fine, we just need to test the container builds and starts - we can add more complex tests at a later date.

**Describe alternatives you've considered**

Fix integration tests and spin up an instance of baw-server. More effort than we're currently willing to invest. 

**Additional context**

**Comment by Allcharles** [comment]
Related issue: #399
