### ISSUE TITLE
Create island component

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#71]
Create an "island" component which is capable of running non angular code inside without affecting the application. The intended purpose for this is to allow the visualizer component from the previous website to run in the new site.

List of requirements:

- Ability to access `<head>` element
  - This includes the ability to import libraries such as JQuery
- Ability to access `<body>` element
- Ability to cleanup leftover timers and orphaned promises

Potentially Relevant Links:

- https://auth0.com/blog/beyond-javascript-frameworks-universal-login-web-component/#Integrating-with-React

**Comment by atruskie** [comment]
For the beta, we're simply going to direct to another hosted site which has the old client running in isolation.

When we get to this issue we'll need to think about where we are up to in terms of porting progress to determine the best path forward.

**Comment by Allcharles** [comment]
Could potentially wrap some functionality in angular zones eg. https://blog.thoughtram.io/angular/2016/02/01/zones-in-angular-2.html
