### ISSUE TITLE
Create table component

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#72]
# Create a reusable table component

This table component should have the following abilities:

- Definable number of columns
- Definable number of rows
- Paging of rows which begins after 20
- Search/Filter at top of table
- Column headers
- Column headers with icons
- Sortable column headers
- Message for if table has no rows
- Cell items can be MenuRoute/MenuLink/MenuAction

**Comment by atruskie** [comment]
We'll use a library. https://swimlane.gitbook.io/ngx-datatable/ looks good - unless you have another suggestion?

**Comment by Allcharles** [comment]
AP Desktop already uses ngx-datatable so it should be a perfect library to use
