### ISSUE TITLE
Emphasis Disabled Menu Links

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#779]
Disabled links in the secondary and action menus could be misleading for users. More emphasis needs to be added to highlight that the links are disabled. Currently the light green colouring given when hovering over the menu item could confuse users into thinking the link is active.

Current State:

![image](https://user-images.githubusercontent.com/3955116/105127784-47ba9c00-5b2d-11eb-8271-b82b564de3f0.png)

**Comment by atruskie** [comment]
maybe `pointer-events: none`?
