### ISSUE TITLE
Remove plumbing from api services

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#78]
Abstract API Services further such that  standardized method names are used (eg. `get`, `getAll`, ...) by all services (Project/Site/User/...). This will further reduce the amount of unit tests and code debt.

Possible implementation is discussed in the following comment: https://github.com/QutEcoacoustics/workbench-client/pull/67#pullrequestreview-345064046. However a workaround will need to be developed for edge case Services such as UserService which will have two `/get` routes (could just split the service).

**Comment by atruskie** [comment]
So the structure I've previously established, which I think will work well again is:

Standard methods:

name | method  | url format | returns collection?
--- | --- | --- | ---
list | GET |  /resource | ✅
show | GET | /resource/:id | ❌
create | POST | /resource | ❌
update | PATCH | /resource/:id | ❌
destroy | DELETE | /resource/:id | ❌
filter | POST |  /resource | ✅

Previously everything that implemented the abstract API methods had to implement ALL the API methods. I'd like it if we could omit the standard methods when appropriate.

Additionally, special case methods should be addable to child service classes when needed.

Example:

```typescript
abstract class AbstractApi<T> {
    authority: string;
    path: string;
}

abstract class ApiList<T> extends AbstractApi<T> {
    list(): T[] {
        console.log(this.path);
        return [];
    }
}
abstract class ApiShow<T> extends AbstractApi<T> {
    show(id: bigint): T {
        return null;
    }
}

// helper types

abstract class StandardApi<T> {
}
interface StandardApi<T> extends ApiShow<T>, ApiList<T> {

}

abstract class ApiWithoutShow<T> {
}
interface ApiWithoutShow<T> extends ApiList<T> {}


 // models

class Project {
    id: bigint;
    name: string;
}

class Site {
    id: bigint;
    name: string;
}

// services 

class ProjectService extends StandardApi<Project> {

    // example special custom method
    requestAccess(projects: Project[]) {
        // blah blah blah
        this.path
    }


}

class SiteService extends ApiWithoutShow<Site> {
    // example resource that does support `show`

    // and a special custom method
    updateOrphan(orphan: Site, newParent: Project) {
        // blah blah blah
        this.path
    }
}

class SiteService2 extends ApiWithoutShow<Site> {
    // example of overriding standard method
    show(id: bigint, parentId: bigint): Site {
        return null;
    }
}

// syntax check

function test() {

    let service = new ProjectService();

    let result: Project = service.show(1n);
    let result2: Project[] = service.list();

    let service2 = new SiteService();

    // Property 'show' does not exist on type 'SiteService'.ts(2339)
    //let result3: Site = service2.show(2);
    
    let result4: Site[] = service2.list();

    let service3 = new SiteService2();
    let result5 = service3.show(3n, 4n);
}
```
