### ISSUE TITLE
Remove id from update requests

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#966]
Baw-server will reject requests to update a model if the models id is part of the body. To remove this issue, update the `apiUpdate` command to remove the `id` property of a model

**Comment by atruskie** [comment]
For context: the body of an update should only contain properties being changed. `id` can't be changed and thus it is an error to send the `id` in the body. Resources are uniquely identified by URL  thus there's no reason to include the `id` in the payload either.

**Comment by Allcharles** [comment]
Played with this idea more, problems run a bit deeper than just the `id` field. Any un-editable fields in a model cannot be sent to the server without an error being returned.
The initial thought which comes to mind is to hijack the attribute decorators (`bawPersistAttr`, `bawImage`, `bawCollection`, etc) and add an `editable` property. This value would be used to track values which can be sent in an update query. Potentially adding an override to `toJSON` or making a `toUpdateModelJson()` function which returns the correct body for the update request.
Another option would be to track which values are actually changed in a model, this would allow us to change the patch request to a put request, and only set the values that have changed. This option comes with a lot of upsides, the biggest being that previously unset values will not be changed to `undefined` when the model is changed by a form.

**Comment by atruskie** [comment]
>  Any un-editable fields in a model cannot be sent to the server without an error being returned.

Makes sense - it is an error to try an update something that cannot be updated. It's worse if things are silently ignored.

> The initial thought which comes to mind is to hijack the attribute decorators (`bawPersistAttr`

Was this not the reason for `bawPersistAttr` in the first place?

> Another option would be to track which values are actually changed in a model, this would allow us to change the patch request to a put request, and only set the values that have changed.

Dirty tracking is quite unreliable IMO.

---

I'd say simplest is augment `bawPersistAttr` so with two flags `create: bool = true, update: bool = true` that both default to true. Then for properties that should be omitted on update/create the model can do the right thing.

Note: our glacial progress towards have an open schema API definition is meant to provide these attributes in a machine readable format - that is not ready yet however.

**Comment by Allcharles** [comment]
On another note, currently the baw-server returns a 500 response when the wrong parameters are given. This should potentially be caught and changed into a bad request message with the list of acceptable inputs
