### ISSUE TITLE
Missing menu links when predicate not met

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#98]
When the user access a page they do not meet the predicate for (eg. Viewing edit project page when not logged in), the menu links for current page do not show up. This could cause confusion for users who use the breadcrumbs to navigate up the chain.

Solution:

Show the menu link, and its lineage, in the secondary menu.

**Comment by atruskie** [comment]
The predicate is not meant to really disable links due to auth reasons.

Its really to show some slightly different options that a more relevant.

Generally, I prefer auth restricted behaviour to show a disabled state with a message explaining why.

TL;DR: yup
