### ISSUE TITLE
Inject api models into components

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#99]
The angular router has the capability to load resources for routes, and inject them into components. This should enable the component to set the api model it requires as an input to the constructor instead of the service.

Example:

Current implementation:

```typescript
  constructor(
    private route: ActivatedRoute,
    private projectsApi: ProjectsService
  )
```

Optimal result:

```typescript
  constructor(
    private route: ActivatedRoute,
    private project: Project
  )
```

Relates to this comment: https://github.com/QutEcoacoustics/workbench-client/pull/93#discussion_r376673658
May relate to this issue: #94

**Comment by Allcharles** [comment]
~~This can be managed through the use of generic injection token functions which return the model or error. Relevant link: https://www.inversionofcontrol.co.uk/injection-tokens-in-angular/~~

**Comment by Allcharles** [comment]
According to this [post](https://stackoverflow.com/a/45737376), accessing the params from the ActivatedRoute is not officially supported outside of the `<router-outlet>` so a workaround will have to be developed.

**Comment by atruskie** [comment]
Yeah, I was confused. I was under the impression that the ui-router project was mainlined into Angular2+, but instead, it is a separate project.

see:

- https://ui-router.github.io/ng2/tutorial/hellosolarsystem
- https://github.com/angular/angular/issues/15032
- https://github.com/angular/angular/issues/9787
- https://github.com/angular/angular/issues/10838

We should use route _resolvers_ where appropriate as per the angular docs: https://angular.io/guide/router#resolve-pre-fetching-component-data

**Comment by atruskie** [comment]
> This can be managed through the use of generic injection token functions which return the model or error. Relevant link: https://www.inversionofcontrol.co.uk/injection-tokens-in-angular/

This was relevant to injecting singular app config settings into services (as per #94). Not relevant for this issue.

**Comment by Allcharles** [comment]
Relevant link: https://codeburst.io/having-fun-with-mixins-in-angular-719f1ec83aeb
